# permissions for end users to edit imagepullsecretinjectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagepullsecretinjector-editor-role
rules:
- apiGroups:
  - secret.w6d.io
  resources:
  - imagepullsecretinjectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secret.w6d.io
  resources:
  - imagepullsecretinjectors/status
  verbs:
  - get
