# permissions for end users to view imagepullsecretinjectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagepullsecretinjector-viewer-role
rules:
- apiGroups:
  - secret.w6d.io
  resources:
  - imagepullsecretinjectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secret.w6d.io
  resources:
  - imagepullsecretinjectors/status
  verbs:
  - get
