---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: imps-injector-role
rules:
- apiGroups:
  - secret.w6d.io
  resources:
  - imagepullsecretinjectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secret.w6d.io
  resources:
  - imagepullsecretinjectors/finalizers
  verbs:
  - update
- apiGroups:
  - secret.w6d.io
  resources:
  - imagepullsecretinjectors/status
  verbs:
  - get
  - patch
  - update
