apiVersion: secret.w6d.io/v1alpha1
kind: ImagePullSecretInjector
metadata:
  name: imagepullsecretinjector-sample
spec:
  secrets:
    - name: secret1
      labels:
        secret1: label
      annotations:
        secret1: annotation
    - name: secret2
      labels:
        secret2: label
      annotations:
        secret2: annotation
  namespaceLabelSelector:
    - key: "kubernetes.io/metadata.name"
      operator: DoesNotStartWith
      value:
        - "kube"